### ISSUE TITLE
Failing black box test: New user cannot use any features until clicking profile

### ISSUE THREAD

**Issue by LoganWilliams1** [michaeldacanay/SlashV2#18]
After registration and signing into slash for the first time, a new user cannot access any authenticated features until they click profile. this is because new users are generated and inserted into the user database only through the profile route. currently there are two solutions to consider:

1) apply the new user generation logic to every authenticated route so that users can immediately access any feature before clicking profile

2) use an Auth0 post-registration webhook to call the addUser api route immediately after registration with Auth0. in our current development efforts this is not possible, but we are looking into the possibility of deploying the app on Red Hat's Kubernetes based OpenShift platform. it may be possible to integrate the Auth0 registration hook with the deployed app.

**Comment by michaeldacanay** [comment]
![image](https://github.com/michaeldacanay/SlashV2/assets/18317412/c347f8a1-0da4-4140-aa0a-07ebc1add099)

**Comment by LoganWilliams1** [comment]
user entity creation added to the search component, the landing page after registration. black box tests passing
