### ISSUE TITLE
Adding User to database table after auth0 login

### ISSUE THREAD

**Issue by michaeldacanay** [michaeldacanay/SlashV2#28]
- When user logins in with auth0, it does not automatically add the user to the database. This causes issues when attempting a search query (indefinitely loading)
- The user currently has to click the "profile" link on the navbar to authenticate (this is kind of on and off, sometimes works and sometimes not, perhaps a race condition?)
- Goal: Move the logic adding the user to the database to an entrypoint in the app so that this discrepancy is resolved

**Comment by michaeldacanay** [comment]
<img width="1131" alt="image" src="https://github.com/michaeldacanay/SlashV2/assets/18317412/2332ace7-64ae-42b8-a236-aee19b3f6598">

This happens if user is logged out, and page is refreshed.

**Comment by michaeldacanay** [comment]
Duplicate of #18 ?

**Comment by LoganWilliams1** [comment]
user entity creation added to the search component, the landing page after registration. black box tests passing
